### PR TITLE
#159987691 Implement SignUp Validation

### PR DESCRIPTION
**Pull request by lauragift21**
#### What does this PR do?
Add validations to user signup inputs
#### Description of Task to be completed?
- add validation logic for user signup endpoints
- write tests for validation logic
#### How should this be manually tested?
-Using Postman to test the `/api/users` endpoint with invalid data, an error will be sent back with a descriptive message.
#### What are the relevant pivotal tracker stories?
 [#159987691](https://www.pivotaltracker.com/story/show/159987691)

### CODE REVIEW

**Review by emekafredy — COMMENTED** [review]
Apart from the HoundCI comments, your code looks good to me. 
Although moving forward, in your PR template, I think you should create the pivotal tracker story link as a markdown, which is clickable, in case the reviewer wants to take a quick look at the story and tasks.
something like this:
 [159987691](https://www.pivotaltracker.com/story/show/159987691)

**Review by gonuoha — APPROVED** [review]
LGTM

**Comment by lauragift21** [comment]
Thanks for the review. @emekafredy I'll fix that asap.

**Comment by aknwosu** [comment]
LGTM

**Pull request merged**
